//
//  MoveData.h
//  pokemongame
//
//  Created by Ian Cordero on 3/3/14.
//  Copyright (c) 2014 Ian Cordero. All rights reserved.
//

#ifndef __pokemongame__MoveData__
#define __pokemongame__MoveData__

#include "constants.h"

#include <string>
using namespace std;

// Move Data

struct MoveData
{
    int ID;
    string name;
    Type type;
    MoveType moveType;
    ContestStat contestStat;
    int PP;
    int damage;
    int accuracy;
    Generation generation;
    MoveEffect effect;
    MoveTarget target;
    bool contact;
    string description;
};

const MoveData movelib[MAXTOTALMOVES] = {
    
    0,  "Struggle", NeutralType,    Status, UnknownStat,    -1, -1, -1, I,	MRecoilStrug,  Opponent, false,
	"",
    1,	"Pound",	NormalType,	Physical,	Tough,	35,	40,	100,	I,	MNoEffect,	Opponent, true,
	"",
    2,	"Karate Chop",	FightingType,	Physical,	Tough,	25,	50,	100,	I,	MHighCrit,	Opponent, true,
	"",
    3,	"Double Slap",	NormalType,	Physical,	Tough,	10,	15,	85,	I,	MDoubleHit,	Opponent, true,
	"",
    4,	"Comet Punch",	NormalType,	Physical,	Tough,	15,	18,	85,	I,	MMultiHit,	Opponent, true,
	"",
    5,	"Mega Punch",	NormalType,	Physical,	Tough,	20,	80,	85,	I,	MNoEffect,	Opponent, true,
	"",
    6,	"Pay Day",	NormalType,	Physical,	Smart,	20,	40,	100,	I,	MPayDay,	Opponent, false,
	"",
    7,	"Fire Punch",	FireType,	Physical,	Beauty,	15,	75,	100,	I,	MBurn15,	Opponent, true,
	"",
    8,	"Ice Punch",	IceType,	Physical,	Beauty,	15,	75,	100,	I,	MFreeze10,	Opponent, true,
	"",
    9,	"Thunder Punch",	ElectricType,	Physical,	Cool,	15,	75,	100,	I,	MParalyze10,	Opponent, true,
	"",
    10,	"Scratch",	NormalType,	Physical,	Tough,	35,	40,	100,	I,	MNoEffect,	Opponent, true,
	"",
    11,	"Vice Grip",	NormalType,	Physical,	Tough,	30,	55,	100,	I,	MNoEffect,	Opponent, true,
	"",
    12,	"Guillotine",	NormalType,	Physical,	Cool,	5,	-1,	30,	I,	MOHKO,	Opponent, true,
	"",
    13,	"Razor Wind",	NormalType,	Special,	Cool,	10,	80,	100,	I,	MRazorwind,	Opponent, false,
	"",
    14,	"Swords Dance",	NormalType,	Status,	Beauty,	20,	-1,	-1,	I,	MUpAtt2,	Self, false,
	"",
    15,	"Cut",	NormalType,	Physical,	Cool,	30,	50,	95,	I,	MNoEffect,	Opponent, true,
	"",
    16,	"Gust",	FlyingType,	Special,	Smart,	35,	40,	100,	I,	MNoEffect,	Opponent, false,
	"",
    17,	"Wing Attack",	FlyingType,	Physical,	Cool,	35,	60,	100,	I,	MNoEffect,	Opponent, true,
	"",
    18,	"Whirlwind",	NormalType,	Status,	Smart,	20,	-1,	-1,	I,	MRoar,	Opponent, false,
	"",
    19,	"Fly",	FlyingType,	Physical,	Smart,	15,	90,	95,	I,	MFly,	Opponent, true,
	"",
    20,	"Bind",	NormalType,	Physical,	Tough,	20,	15,	85,	I,	MBind,	Opponent, true,
	"",
    21,	"Slam",	NormalType,	Physical,	Tough,	20,	80,	75,	I,	MNoEffect,	Opponent, true,
	"",
    22,	"Vine Whip",	GrassType,	Physical,	Cool,	25,	45,	100,	I,	MNoEffect,	Opponent, true,
	"",
    23,	"Stomp",	NormalType,	Physical,	Tough,	20,	65,	100,	I,	MFlinch30,	Opponent, true,
	"",
    24,	"Double Kick",	FightingType,	Physical,	Cool,	30,	30,	100,	I,	MDoubleHit,	Opponent, true,
	"",
    25,	"Mega Kick",	NormalType,	Physical,	Cool,	5,	120,	75,	I,	MNoEffect,	Opponent, true,
	"",
    26,	"Jump Kick",	FightingType,	Physical,	Cool,	10,	100,	95,	I,	MJumpKick,	Opponent, true,
	"",
    27,	"Rolling Kick",	FightingType,	Physical,	Cool,	15,	60,	85,	I,  MFlinch30,	Opponent, true,
	"",
    28,	"Sand Attack",	GroundType,	Status,	Cute,	15,	-1,	100,	I,	MLowerAcc,	Opponent, false,
	"",
    29,	"Headbutt",	NormalType,	Physical,	Tough,	15,	70,	100,	I,	MFlinch30,	Opponent, true,
	"",
    30,	"Horn Attack",	NormalType,	Physical,	Cool,	25,	65,	100,	I,	MNoEffect,	Opponent, true,
	"",
    31,	"Fury Attack",	NormalType,	Physical,	Cool,	20,	15,	85,	I,	MMultiHit,	Opponent, true,
	"",
    32,	"Horn Drill",	NormalType,	Physical,	Cool,	5,	-1,	30,	I,	MOHKO,	Opponent,   true,
	"",
    33,	"Tackle",	NormalType,	Physical,	Tough,	35,	50,	100,	I,	MNoEffect,	Opponent, true,
	"",
    34,	"Body Slam",	NormalType,	Physical,	Tough,	15,	85,	100,	I,	MParalyze30,	Opponent, true,
	"",
    35,	"Wrap",	NormalType,	Physical,	Tough,	20,	15,	90,	I,	MWrap,	Opponent, true,
	"",
    36,	"Take Down",	NormalType,	Physical,	Tough,	20,	90,	85,	I,	MRecoil25,	Opponent, true,
	"",
    37,	"Thrash",	NormalType,	Physical,	Tough,	10,	120,	100,	I,	MRampage,	Opponent, true,
	"",
    38,	"Double-Edge",	NormalType,	Physical,	Tough,	15,	120,	100,	I,	MRecoil33,	Opponent, true,
	"",
    39,	"Tail Whip",	NormalType,	Status,	Cute,	30,	-1,	100,	I,	MLowerDef,	Both, false,
	"",
    40,	"Poison Sting",	PoisonType,	Physical,	Smart,	35,	15,	100,	I,	MPoison30,	Opponent, false,
	"",
    41,	"Twineedle",	BugType,	Physical,	Cool,	20,	25,	100,	I,	MDoubleHit,	Opponent, false,
	"",
    42,	"Pin Missile",	BugType,	Physical,	Cool,	20,	25,	95,	I,	MMultiHit,	Opponent, false,
	"",
    43,	"Leer",	NormalType,	Status,	Cool,	30,	-1,	100,	I,	MLowerDef,	Both, false,
	"",
    44,	"Bite",	DarkType,	Physical,	Tough,	25,	60,	100,	I,	MFlinch30,	Opponent, true,
	"",
    45,	"Growl",	NormalType,	Status,	Cute,	40,	-1,	100,	I,	MLowerAtt,	Opponent, false,
	"",
    46,	"Roar",	NormalType,	Status,	Cool,	20,	-1,	-1,	I,	MRoar,	Opponent, false,
	"",
    47,	"Sing",	NormalType,	Status,	Cute,	15,	-1,	55,	I,	MSleep,	Opponent, false,
	"",
    48,	"Supersonic",	NormalType,	Status,	Smart,	20,	-1,	55,	I,	MConfuse,	Opponent, false,
	"",
    49,	"Sonic Boom",	NormalType,	Special,	Cool,	20, -1, 90,	I,	MDamage20,	Opponent, false,
	"",
    50,	"Disable",	NormalType,	Status,	Smart,	20,	-1,	100,	I,	MDisable,	Opponent, false,
	"",
    51,	"Acid",	PoisonType,	Special,	Smart,	30,	40,	100,	I,	MLowerSpD10,	Both, false,
	"",
    52,	"Ember",	FireType,	Special,	Beauty,	25,	40,	100,	I,	MBurn10,	Opponent, false,
	"",
    53,	"Flamethrower",	FireType,	Special,	Beauty,	15,	90,	100,	I,	MBurn10,	Opponent, false,
	"",
    54,	"Mist",	IceType,	Status,	Beauty,	30,	-1,	-1,	I,	MNoEffect,	Opponent, false,
	"",
    55,	"Water Gun",	WaterType,	Special,	Cute,	25,	40,	100,	I,	MNoEffect,	Opponent, false,
	"",
    56,	"Hydro Pump",	WaterType,	Special,	Beauty,	5,	110,	80,	I,	MNoEffect,	Opponent, false,
	"",
    57,	"Surf",	WaterType,	Special,	Beauty,	15,	90,	100,	I,	MNoEffect,	All, false,
	"",
    58,	"Ice Beam",	IceType,	Special,	Beauty,	10,	90,	100,	I,	MFreeze10,	Opponent, false,
	"",
    59,	"Blizzard",	IceType,	Special,	Beauty,	5,	110,	70,	I,	MFreeze10,	Opponent, false,
	"",
    60,	"Psybeam",	PsychicType,	Special,	Beauty,	20,	65,	100,	I,	MNoEffect,	Opponent, false,
	"",
    61,	"Bubble Beam",	WaterType,	Special,	Beauty,	20,	65,	100,	I,	MNoEffect,	Opponent, false,
	"",
    62,	"Aurora Beam",	IceType,	Special,	Beauty,	20,	65,	100,	I,	MNoEffect,	Opponent, false,
	"",
    63,	"Hyper Beam",	NormalType,	Special,	Cool,	5,	150,	90,	I,	MRecharge,	Opponent, false,
	"",
    64,	"Peck",	FlyingType,	Physical,	Cool,	35,	35,	100,	I,	MNoEffect,	Opponent, true,
	"",
    65,	"Drill Peck",	FlyingType,	Physical,	Cool,	20,	80,	100,	I,	MNoEffect,	Opponent, true,
	"",
    66,	"Submission",	FightingType,	Physical,	Cool,	25,	80,	80,	I,	MRecoil25,	Opponent, true,
	"",
    67,	"Low Kick",	FightingType,	Physical,	Tough,	20,	-1,	100,	I,	MNoEffect,	Opponent, true,
	"",
    68,	"Counter",	FightingType,	Physical,	Tough,	20,	-1,	100,	I,	MNoEffect,	Opponent, true,
	"",
    69,	"Seismic Toss",	FightingType,	Physical,	Tough,	20,	-1,	100,	I,	MDamageLevel,	Opponent, true,
	"",
    70,	"Strength",	NormalType,	Physical,	Tough,	15,	80,	100,	I,	MNoEffect,	Opponent, true,
	"",
    71,	"Absorb",	GrassType,	Special,	Smart,	25,	20,	100,	I,	MDrain50,	Opponent, false,
	"",
    72,	"Mega Drain",	GrassType,	Special,	Smart,	15,	40,	100,	I,	MDrain50,	Opponent, false,
	"",
    73,	"Leech Seed",	GrassType,	Status,	Smart,	10,	-1,	90,	I,	MNoEffect,	Opponent, false,
	"",
    74,	"Growth",	NormalType,	Status,	Beauty,	20,	-1,	-1,	I,	MUpAttSpA,	Opponent, false,
	"",
    75,	"Razor Leaf",	GrassType,	Physical,	Cool,	25,	55,	95,	I,	MHighCrit,	Opponent, false,
	"",
    76,	"Solar Beam",	GrassType,	Special,	Cool,	10,	120,	100,	I,	MSolarbeam,	Opponent, false,
	"",
    77,	"Poison Powder",	PoisonType,	Status,	Smart,	35,	-1,	75,	I,	MPoison,	Opponent, false,
	"",
    78,	"Stun Spore",	GrassType,	Status,	Smart,	30,	-1,	75,	I,	MParalyze,	Opponent, false,
	"",
    79,	"Sleep Powder",	GrassType,	Status,	Smart,	15,	-1,	75,	I,	MSleep,	Opponent, false,
	"",
    80,	"Petal Dance",	GrassType,	Special,	Beauty,	10,	120,	100,	I,	MRampage,	Opponent, true,
	"",
    81,	"String Shot",	BugType,	Status,	Smart,	40,	-1,	95,	I,	MLowerSpe,	Opponent, false,
	"",
    82,	"Dragon Rage",	DragonType,	Special,	Cool,	10,	-1, 100,	I,	MDamage40,	Opponent, false,
	"",
    83,	"Fire Spin",	FireType,	Special,	Beauty,	15,	35,	85,	I,	MFireSpin,	Opponent, false,
	"",
    84,	"Thunder Shock",	ElectricType,	Special,	Cool,	30,	40,	100,	I,	MParalyze10,	Opponent, false,
	"",
    85,	"Thunderbolt",	ElectricType,	Special,	Cool,	15,	90,	100,	I,	MParalyze10,	Opponent, false,
	"",
    86,	"Thunder Wave",	ElectricType,	Status,	Cool,	20,	-1,	100,	I,	MParalyze,	Opponent, false,
	"",
    87,	"Thunder",	ElectricType,	Special,	Cool,	10,	110,	70,	I,	MParalyze30,	Opponent, false,
	"",
    88,	"Rock Throw",	RockType,	Physical,	Tough,	15,	50,	90,	I,	MNoEffect,	Opponent, false,
	"",
    89,	"Earthquake",	GroundType,	Physical,	Tough,	10,	100,	100,	I,	MNoEffect,	Opponent, false,
	"",
    90,	"Fissure",	GroundType,	Physical,	Tough,	5,	-1,	30,	I,	MOHKO,	Opponent, false,
	"",
    91,	"Dig",	GroundType,	Physical,	Smart,	10,	80,	100,	I,	MDig,	Opponent, true,
	"",
    92,	"Toxic",	PoisonType,	Status,	Smart,	10,	-1,	90,	I,	MToxic,	Opponent, false,
	"",
    93,	"Confusion",	PsychicType,	Special,	Smart,	25,	50,	100,	I,	MConfuse10,	Opponent, false,
	"",
    94,	"Psychic",	PsychicType,	Special,	Smart,	10,	90,	100,	I,	MLowerSpD10,	Opponent, false,
	"",
    95,	"Hypnosis",	PsychicType,	Status,	Smart,	20,	-1,	60,	I,	MSleep,	Opponent, false,
	"",
    96,	"Meditate",	PsychicType,	Status,	Beauty,	40,	-1,	-1,	I,	MUpAtt,	Self, false,
	"",
    97,	"Agility",	PsychicType,	Status,	Cool,	30,	-1,	-1,	I,	MUpSpe2,	Self, false,
	"",
    98,	"Quick Attack",	NormalType,	Physical,	Cool,	30,	40,	100,	I,	MMoveFirst,	Opponent, true,
	"",
    99,	"Rage",	NormalType,	Physical,	Cool,	20,	20,	100,	I,	MRage,	Opponent, true,
	"",
    100,	"Teleport",	PsychicType,	Status,	Cool,	20,	-1,	-1,	I,	MTeleport,	Self, false,
	"",
    101,	"Night Shade",	GhostType,	Special,	Smart,	15,	-1,	100,	I,	MDamageLevel,	Opponent, false,
	"",
    102,	"Mimic",	NormalType,	Status,	Cute,	10,	-1,	100,	I,	MNoEffect,	Opponent, false,
	"",
    103,	"Screech",	NormalType,	Status,	Smart,	40,	-1,	85,	I,	MLowerDef2,	Opponent, false,
	"",
    104,	"Double Team",	NormalType,	Status,	Cool,	15,	-1,	-1,	I,	MUpEva,	Self, false,
	"",
    105,	"Recover",	NormalType,	Status,	Smart,	10,	-1,	-1,	I,	MHeal50,	Self, false,
	"",
    106,	"Harden",	NormalType,	Status,	Tough,	30,	-1,	-1,	I,	MUpDef,	Self, false,
	"",
    107,	"Minimize",	NormalType,	Status,	Cute,	10,	-1,	-1,	I,	MUpEva2,	Self, false,
	"",
    108,	"Smokescreen",	NormalType,	Status,	Smart,	20,	-1,	100,	I,	MLowerAcc,	Opponent, false,
	"",
    109,	"Confuse Ray",	GhostType,	Status,	Smart,	10,	-1,	100,	I,	MConfuse,	Opponent, false,
	"",
    110,	"Withdraw",	WaterType,	Status,	Cute,	40,	-1,	-1,	I,	MUpDef,	Self, false,
	"",
    111,	"Defense Curl",	NormalType,	Status,	Cute,	40,	-1,	-1,	I,	MUpDef,	Self, false,
	"",
    112,	"Barrier",	PsychicType,	Status,	Cool,	20,	-1,	-1,	I,	MUpDef2,	Self, false,
	"",
    113,	"Light Screen",	PsychicType,	Status,	Beauty,	30,	-1,	-1,	I,	MLightScreen,	Self, false,
	"",
    114,	"Haze",	IceType,	Status,	Beauty,	30,	-1,	-1,	I,	MNoEffect,	Opponent, false,
	"",
    115,	"Reflect",	PsychicType,	Status,	Smart,	20,	-1,	-1,	I,	MReflect,	Self, false,
	"",
    116,	"Focus Energy",	NormalType,	Status,	Cool,	30,	-1,	-1,	I,	MNoEffect,	Opponent, false,
	"",
    117,	"Bide",	NormalType,	Physical,	Tough,	10,	-1,	100,	I,	MNoEffect,	Opponent, true,
	"",
    118,	"Metronome",	NormalType,	Status,	Cute,	10,	-1,	-1,	I,	MNoEffect,	Opponent, false,
	"",
    119,	"Mirror Move",	FlyingType,	Status,	Smart,	20,	-1,	-1,	I,	MNoEffect,	Opponent, false,
	"",
    120,	"Self-Destruct",	NormalType,	Physical,	Beauty,	5,	200,	100,	I,	MSelfdestruct,	All, false,
	"",
    121,	"Egg Bomb",	NormalType,	Physical,	Tough,	10,	100,	75,	I,	MNoEffect,	Opponent, false,
	"",
    122,	"Lick",	GhostType,	Physical,	Tough,	30,	30,	100,	I,	MNoEffect,	Opponent, true,
	"",
    123,	"Smog",	PoisonType,	Special,	Tough,	20,	30,	70,	I,	MPoison40,	Opponent, false,
	"",
    124,	"Sludge",	PoisonType,	Special,	Tough,	20,	65,	100,	I,	MPoison30,	Opponent, false,
	"",
    125,	"Bone Club",	GroundType,	Physical,	Tough,	20,	65,	85,	I,	MNoEffect,	Opponent, false,
	"",
    126,	"Fire Blast",	FireType,	Special,	Beauty,	5,	110,	85,	I,	MBurn15,	Opponent, false,
	"",
    127,	"Waterfall",	WaterType,	Physical,	Tough,	15,	80,	100,	I,	MFlinch20,	Opponent, true,
	"",
    128,	"Clamp",	WaterType,	Physical,	Tough,	10,	35,	85,	I,	MNoEffect,	Opponent, true,
	"",
    129,	"Swift",	NormalType,	Special,	Cool,	20,	60,	-1,	I,	MNeverMiss,	Opponent, false,
	"",
    130,	"Skull Bash",	NormalType,	Physical,	Tough,	10,	130,	100,	I,	MSkullbash,	Opponent, true,
	"",
    131,	"Spike Cannon",	NormalType,	Physical,	Cool,	15,	20,	100,	I,	MMultiHit,	Opponent, false,
	"",
    132,	"Constrict",	NormalType,	Physical,	Tough,	35,	10,	100,	I,	MNoEffect,	Opponent, true,
	"",
    133,	"Amnesia",	PsychicType,	Status,	Cute,	20,	-1,	-1,	I,	MUpSpD2,	Self, false,
	"",
    134,	"Kinesis",	PsychicType,	Status,	Smart,	15,	-1,	80,	I,	MNoEffect,	Opponent, false,
	"",
    135,	"Soft-Boiled",	NormalType,	Status,	Beauty,	10,	-1,	-1,	I,	MHeal50,	Self, false,
	"",
    136,	"High Jump Kick",	FightingType,	Physical,	Cool,	10,	130,	90,	I,	MNoEffect,	Opponent, true,
	"",
    137,	"Glare",	NormalType,	Status,	Tough,	30,	-1,	100,	I,	MParalyze,	Opponent, false,
	"",
    138,	"Dream Eater",	PsychicType,	Special,	Smart,	15,	100,	100,	I,	MDrain50,	Opponent, false,
	"",
    139,	"Poison Gas",	PoisonType,	Status,	Smart,	40,	-1,	90,	I,	MNoEffect,	Opponent, false,
	"",
    140,	"Barrage",	NormalType,	Physical,	Tough,	20,	15,	85,	I,	MNoEffect,	Opponent, false,
	"",
    141,	"Leech Life",	BugType,	Physical,	Smart,	15,	20,	100,	I,	MNoEffect,	Opponent, true,
	"",
    142,	"Lovely Kiss",	NormalType,	Status,	Beauty,	10,	-1,	75,	I,	MNoEffect,	Opponent, false,
	"",
    143,	"Sky Attack",	FlyingType,	Physical,	Cool,	5,	140,	90,	I,	MSkyAttack,	Opponent, false,
	"",
    144,	"Transform",	NormalType,	Status,	Smart,	10,	-1,	-1,	I,	MNoEffect,	Opponent, false,
	"",
    145,	"Bubble",	WaterType,	Special,	Cute,	30,	40,	100,	I,	MNoEffect,	Opponent, false,
	"",
    146,	"Dizzy Punch",	NormalType,	Physical,	Cool,	10,	70,	100,	I,	MNoEffect,	Opponent, true,
	"",
    147,	"Spore",	GrassType,	Status,	Beauty,	15,	-1,	100,	I,	MSleep,	Opponent, false,
	"",
    148,	"Flash",	NormalType,	Status,	Beauty,	20,	-1,	100,	I,	MNoEffect,	Opponent, false,
	"",
    149,	"Psywave",	PsychicType,	Special,	Smart,	15,	-1,	100,	I,	MNoEffect,	Opponent, false,
	"",
    150,	"Splash",	NormalType,	Status,	Cute,	40,	-1,	-1,	I,	MNoEffect,	Opponent, false,
	"",
    151,	"Acid Armor",	PoisonType,	Status,	Tough,	20,	-1,	-1,	I,	MUpDef2,	Self, false,
	"",
    152,	"Crabhammer",	WaterType,	Physical,	Tough,	10,	100,	90,	I,	MHighCrit,	Opponent, true,
	"",
    153,	"Explosion",	NormalType,	Physical,	Beauty,	5,	250,	100,	I,	MSelfdestruct,	All, false,
	"",
    154,	"Fury Swipes",	NormalType,	Physical,	Tough,	15,	18,	80,	I,	MNoEffect,	Opponent, true,
	"",
    155,	"Bonemerang",	GroundType,	Physical,	Tough,	10,	50,	90,	I,	MNoEffect,	Opponent, false,
	"",
    156,	"Rest",	PsychicType,	Status,	Cute,	10,	-1,	-1,	I,	MHeal100,	Self, false,
	"",
    157,	"Rock Slide",	RockType,	Physical,	Tough,	10,	75,	90,	I,	MNoEffect,	Opponent, false,
	"",
    158,	"Hyper Fang",	NormalType,	Physical,	Cool,	15,	80,	90,	I,	MNoEffect,	Opponent, true,
	"",
    159,	"Sharpen",	NormalType,	Status,	Cute,	30,	-1,	-1,	I,	MUpAtt,	Self, false,
	"",
    160,	"Conversion",	NormalType,	Status,	Beauty,	30,	-1,	-1,	I,	MNoEffect,	Opponent, false,
	"",
    161,	"Tri Attack",	NormalType,	Special,	Beauty,	10,	80,	100,	I,	MTri20,	Opponent, false,
	"",
    162,	"Super Fang",	NormalType,	Physical,	Tough,	10,	-1,	90,	I,	MNoEffect,	Opponent, true,
	"",
    163,	"Slash",	NormalType,	Physical,	Cool,	20,	70,	100,	I,	MHighCrit,	Opponent, true,
	"",
    164,	"Substitute",	NormalType,	Status,	Smart,	10,	-1,	-1,	I,	MSub,	Opponent, false,
	"",
    165,	"Struggle",	NormalType,	Physical,	Cool,	1,	50,	100,	I,	MNoEffect,	Opponent, true,
	"",
    166,	"Sketch",	NormalType,	Status,	Smart,	1,	-1,	-1,	II,	MNoEffect,	Opponent, false,
	"",
    167,	"Triple Kick",	FightingType,	Physical,	Cool,	10,	10,	90,	II,	MMultiHit,	Opponent, true,
	"",
    168,	"Thief",	DarkType,	Physical,	Tough,	25,	60,	100,	II,	MNoEffect,	Opponent, true,
	"",
    169,	"Spider Web",	BugType,	Status,	Smart,	10,	-1,	100,	II,	MTrap,	Opponent, false,
	"",
    170,	"Mind Reader",	NormalType,	Status,	Smart,	5,	-1,	100,	II,	MNoEffect,	Opponent, false,
	"",
    171,	"Nightmare",	GhostType,	Status,	Smart,	15,	-1,	100,	II,	MNoEffect,	Opponent, false,
	"",
    172,	"Flame Wheel",	FireType,	Physical,	Beauty,	25,	60,	100,	II,	MNoEffect,	Opponent, true,
	"",
    173,	"Snore",	NormalType,	Special,	Cute,	15,	50,	100,	II,	MNoEffect,	Opponent, false,
	"",
    174,	"Curse",	GhostType,	Status,	Tough,	10,	-1,	-1,	II,	MNoEffect,	Opponent, false,
	"",
    175,	"Flail",	NormalType,	Physical,	Cute,	15,	-1,	100,	II,	MNoEffect,	Opponent, true,
	"",
    176,	"Conversion 2",	NormalType,	Status,	Beauty,	30,	-1,	100,	II,	MNoEffect,	Opponent, false,
	"",
    177,	"Aeroblast",	FlyingType,	Special,	Cool,	5,	100,	95,	II,	MHighCrit,	Opponent, false,
	"",
    178,	"Cotton Spore",	GrassType,	Status,	Beauty,	40,	-1,	100,	II,	MNoEffect,	Opponent, false,
	"",
    179,	"Reversal",	FightingType,	Physical,	Cool,	15,	-1,	100,	II,	MNoEffect,	Opponent, true,
	"",
    180,	"Spite",	GhostType,	Status,	Tough,	10,	-1,	100,	II,	MNoEffect,	Opponent, false,
	"",
    181,	"Powder Snow",	IceType,	Special,	Beauty,	25,	40,	100,	II,	MNoEffect,	Opponent, false,
	"",
    182,	"Protect",	NormalType,	Status,	Cute,	10,	-1,	-1,	II,	MProtect,	Self, false,
	"",
    183,	"Mach Punch",	FightingType,	Physical,	Cool,	30,	40,	100,	II,	MMoveFirst,	Opponent, true,
	"",
    184,	"Scary Face",	NormalType,	Status,	Tough,	10,	-1,	100,	II,	MLowerSpe2,	Opponent, false,
	"",
    185,	"Feint Attack",	DarkType,	Physical,	Smart,	20,	60,	-1,	II,	MNeverMiss,	Opponent, true,
	"",
    186,	"Sweet Kiss",	FairyType,	Status,	Cute,	10,	-1,	75,	II,	MConfuse,	Opponent, false,
	"",
    187,	"Belly Drum",	NormalType,	Status,	Cute,	10,	-1,	-1,	II,	MNoEffect,	Opponent, false,
	"",
    188,	"Sludge Bomb",	PoisonType,	Special,	Tough,	10,	90,	100,	II,	MPoison30,	Opponent, false,
	"",
    189,	"Mud-Slap",	GroundType,	Special,	Cute,	10,	20,	100,	II,	MLowerAcc100,	Opponent, false,
	"",
    190,	"Octazooka",	WaterType,	Special,	Tough,	10,	65,	85,	II,	MNoEffect,	Opponent, false,
	"",
    191,	"Spikes",	GroundType,	Status,	Smart,	20,	-1,	-1,	II,	MHazard,	Opponent, false,
	"",
    192,	"Zap Cannon",	ElectricType,	Special,	Cool,	5,	120,	50,	II,	MParalyze100,	Opponent, false,
	"",
    193,	"Foresight",	NormalType,	Status,	Smart,	40,	-1,	100,	II,	MNoEffect,	Opponent, false,
	"",
    194,	"Destiny Bond",	GhostType,	Status,	Smart,	5,	-1,	-1,	II,	MNoEffect,	Opponent, false,
	"",
    195,	"Perish Song",	NormalType,	Status,	Beauty,	5,	-1,	-1,	II,	MNoEffect,	Opponent, false,
	"",
    196,	"Icy Wind",	IceType,	Special,	Beauty,	15,	55,	95,	II,	MNoEffect,	Opponent, false,
	"",
    197,	"Detect",	FightingType,	Status,	Cool,	5,	-1,	-1,	II,	MProtect,	Self, false,
	"",
    198,	"Bone Rush",	GroundType,	Physical,	Tough,	10,	25,	90,	II,	MNoEffect,	Opponent, false,
	"",
    199,	"Lock-On",	NormalType,	Status,	Smart,	5,	-1,	100,	II,	MNoEffect,	Opponent, false,
	"",
    200,	"Outrage",	DragonType,	Physical,	Cool,	15,	120,	100,	II,	MRampage,	Opponent, true,
	"",
    201,	"Sandstorm",	RockType,	Status,	Tough,	10,	-1,	-1,	II,	MSandstorm,	None, false,
	"",
    202,	"Giga Drain",	GrassType,	Special,	Smart,	10,	75,	100,	II,	MDrain50,	Opponent, false,
	"",
    203,	"Endure",	NormalType,	Status,	Tough,	10,	-1,	-1,	II,	MNoEffect,	Opponent, false,
	"",
    204,	"Charm",	FairyType,	Status,	Cute,	20,	-1,	100,	II,	MLowerAtt,	Opponent, false,
	"",
    205,	"Rollout",	RockType,	Physical,	Tough,	20,	30,	90,	II,	MNoEffect,	Opponent, true,
	"",
    206,	"False Swipe",	NormalType,	Physical,	Cool,	40,	40,	100,	II,	MNoEffect,	Opponent, true,
	"",
    207,	"Swagger",	NormalType,	Status,	Cute,	15,	-1,	90,	II,	MConfuse,	Opponent, false,
	"",
    208,	"Milk Drink",	NormalType,	Status,	Cute,	10,	-1,	-1,	II,	MHeal50,	Self, false,
	"",
    209,	"Spark",	ElectricType,	Physical,	Cool,	20,	65,	100,	II,	MParalyze30,	Opponent, true,
	"",
    210,	"Fury Cutter",	BugType,	Physical,	Cool,	20,	40,	95,	II,	MNoEffect,	Opponent, true,
	"",
    211,	"Steel Wing",	SteelType,	Physical,	Cool,	25,	70,	90,	II,	MUpDef10,	Opponent, true,
	"",
    212,	"Mean Look",	NormalType,	Status,	Beauty,	5,	-1,	100,	II,	MTrap,	Opponent, false,
	"",
    213,	"Attract",	NormalType,	Status,	Cute,	15,	-1,	100,	II,	MNoEffect,	Opponent, false,
	"",
    214,	"Sleep Talk",	NormalType,	Status,	Cute,	10,	-1,	-1,	II,	MNoEffect,	Opponent, false,
	"",
    215,	"Heal Bell",	NormalType,	Status,	Beauty,	5,	-1,	-1,	II,	MNoEffect,	Opponent, false,
	"",
    216,	"Return",	NormalType,	Physical,	Cute,	20,	-1,	100,	II,	MNoEffect,	Opponent, true,
	"",
    217,	"Present",	NormalType,	Physical,	Cute,	15,	-1,	90,	II,	MNoEffect,	Opponent, false,
	"",
    218,	"Frustration",	NormalType,	Physical,	Cute,	20,	-1,	100,	II,	MNoEffect,	Opponent, true,
	"",
    219,	"Safeguard",	NormalType,	Status,	Beauty,	25,	-1,	-1,	II,	MNoEffect,	Opponent, false,
	"",
    220,	"Pain Split",	NormalType,	Status,	Smart,	20,	-1,	100,	II,	MNoEffect,	Opponent, false,
	"",
    221,	"Sacred Fire",	FireType,	Physical,	Beauty,	5,	100,	95,	II,	MNoEffect,	Opponent, false,
	"",
    222,	"Magnitude",	GroundType,	Physical,	Tough,	30,	-1,	100,	II,	MNoEffect,	Opponent, false,
	"",
    223,	"Dynamic Punch",	FightingType,	Physical,	Cool,	5,	100,	50,	II,	MNoEffect,	Opponent, true,
	"",
    224,	"Megahorn",	BugType,	Physical,	Cool,	10,	120,	85,	II,	MNoEffect,	Opponent, true,
	"",
    225,	"Dragon Breath",	DragonType,	Special,	Cool,	20,	60,	100,	II,	MNoEffect,	Opponent, false,
	"",
    226,	"Baton Pass",	NormalType,	Status,	Cute,	40,	-1,	-1,	II,	MNoEffect,	Opponent, false,
	"",
    227,	"Encore",	NormalType,	Status,	Cute,	5,	-1,	100,	II,	MNoEffect,	Opponent, false,
	"",
    228,	"Pursuit",	DarkType,	Physical,	Smart,	20,	40,	100,	II,	MNoEffect,	Opponent, true,
	"",
    229,	"Rapid Spin",	NormalType,	Physical,	Cool,	40,	20,	100,	II,	MDehazard,	Opponent, true,
	"",
    230,	"Sweet Scent",	NormalType,	Status,	Cute,	20,	-1,	100,	II,	MLowerEva,	Opponent, false,
	"",
    231,	"Iron Tail",	SteelType,	Physical,	Cool,	15,	100,	75,	II,	MNoEffect,	Opponent, true,
	"",
    232,	"Metal Claw",	SteelType,	Physical,	Cool,	35,	50,	95,	II,	MNoEffect,	Opponent, true,
	"",
    233,	"Vital Throw",	FightingType,	Physical,	Cool,	10,	70,	100,	II,	MVitalThrow,	Opponent, true,
	"",
    234,	"Morning Sun",	NormalType,	Status,	Beauty,	5,	-1,	-1,	II,	MHeal50,	Self, false,
	"",
    235,	"Synthesis",	GrassType,	Status,	Smart,	5,	-1,	-1,	II,	MHeal50,	Self, false,
	"",
    236,	"Moonlight",	FairyType,	Status,	Beauty,	5,	-1,	-1,	II,	MHeal50,	Self, false,
	"",
    237,	"Hidden Power",	NormalType,	Special,	Smart,	15,	60,	100,	II,	MNoEffect,	Opponent, false,
	"",
    238,	"Cross Chop",	FightingType,	Physical,	Cool,	5,	100,	80,	II,	MHighCrit,	Opponent, true,
	"",
    239,	"Twister",	DragonType,	Special,	Cool,	20,	40,	100,	II,	MFlinch20,	Opponent, false,
	"",
    240,	"Rain Dance",	WaterType,	Status,	Tough,	5,	-1,	-1,	II,	MRain,	None, false,
	"",
    241,	"Sunny Day",	FireType,	Status,	Beauty,	5,	-1,	-1,	II,	MSun,	None, false,
	"",
    242,	"Crunch",	DarkType,	Physical,	Tough,	15,	80,	100,	II,	MNoEffect,	Opponent, true,
	"",
    243,	"Mirror Coat",	PsychicType,	Special,	Beauty,	20,	-1,	100,	II,	MNoEffect,	Opponent, false,
	"",
    244,	"Psych Up",	NormalType,	Status,	Smart,	10,	-1,	-1,	II,	MNoEffect,	Opponent, false,
	"",
    245,	"Extreme Speed",	NormalType,	Physical,	Cool,	5,	80,	100,	II,	MMoveFirst,	Opponent, true,
	"",
    246,	"Ancient Power",	RockType,	Special,	Tough,	5,	60,	100,	II,	MUpAll10,	Opponent, false,
	"",
    247,	"Shadow Ball",	GhostType,	Special,	Smart,	15,	80,	100,	II,	MLowerSpD20,	Opponent, false,
	"",
    248,	"Future Sight",	PsychicType,	Special,	Smart,	10,	120,	100,	II,	MNoEffect,	Opponent, false,
	"",
    249,	"Rock Smash",	FightingType,	Physical,	Tough,	15,	40,	100,	II,	MNoEffect,	Opponent, true,
	"",
    250,	"Whirlpool",	WaterType,	Special,	Beauty,	15,	35,	85,	II,	MWhirlpool,	Opponent, false,
	"",
    251,	"Beat Up",	DarkType,	Physical,	Smart,	10,	-1,	100,	II,	MNoEffect,	Opponent, false,
	"",
    252,	"Fake Out",	NormalType,	Physical,	Cute,	10,	40,	100,	III,	MNoEffect,	Opponent, true,
	"",
    253,	"Uproar",	NormalType,	Special,	Cute,	10,	90,	100,	III,	MRampage,	Opponent, false,
	"",
    254,	"Stockpile",	NormalType,	Status,	Tough,	20,	-1,	-1,	III,	MNoEffect,	Opponent, false,
	"",
    255,	"Spit Up",	NormalType,	Special,	Tough,	10,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    256,	"Swallow",	NormalType,	Status,	Tough,	10,	-1,	-1,	III,	MNoEffect,	Opponent, false,
	"",
    257,	"Heat Wave",	FireType,	Special,	Beauty,	10,	95,	90,	III,	MNoEffect,	Opponent, false,
	"",
    258,	"Hail",	IceType,	Status,	Beauty,	10,	-1,	-1,	III,	MHail,	None, false,
	"",
    259,	"Torment",	DarkType,	Status,	Tough,	15,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    260,	"Flatter",	DarkType,	Status,	Smart,	15,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    261,	"Will-O-Wisp",	FireType,	Status,	Beauty,	15,	-1,	85,	III,	MBurn,	Opponent, false,
	"",
    262,	"Memento",	DarkType,	Status,	Tough,	10,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    263,	"Facade",	NormalType,	Physical,	Cute,	20,	70,	100,	III,	MNoEffect,	Opponent, true,
	"",
    264,	"Focus Punch",	FightingType,	Physical,	Tough,	20,	150,	100,	III,	MFocusPunch,	Opponent, true,
	"",
    265,	"Smelling Salts",	NormalType,	Physical,	Smart,	10,	70,	100,	III,	MNoEffect,	Opponent, true,
	"",
    266,	"Follow Me",	NormalType,	Status,	Cute,	20,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    267,	"Nature Power",	NormalType,	Status,	Beauty,	20,	-1,	-1,	III,	MNoEffect,	Opponent, false,
	"",
    268,	"Charge",	ElectricType,	Status,	Smart,	20,	-1,	-1,	III,	MNoEffect,	Opponent, false,
	"",
    269,	"Taunt",	DarkType,	Status,	Smart,	20,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    270,	"Helping Hand",	NormalType,	Status,	Smart,	20,	-1,	-1,	III,	MNoEffect,	Opponent, false,
	"",
    271,	"Trick",	PsychicType,	Status,	Smart,	10,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    272,	"Role Play",	PsychicType,	Status,	Cute,	10,	-1,	-1,	III,	MNoEffect,	Opponent, false,
	"",
    273,	"Wish",	NormalType,	Status,	Cute,	10,	-1,	-1,	III,	MHeal50,	Self, false,
	"",
    274,	"Assist",	NormalType,	Status,	Cute,	20,	-1,	-1,	III,	MNoEffect,	Opponent, false,
	"",
    275,	"Ingrain",	GrassType,	Status,	Smart,	20,	-1,	-1,	III,	MNoEffect,	Opponent, false,
	"",
    276,	"Superpower",	FightingType,	Physical,	Tough,	5,	120,	100,	III,	MSuperpower,	Opponent, true,
	"",
    277,	"Magic Coat",	PsychicType,	Status,	Beauty,	15,	-1,	-1,	III,	MNoEffect,	Opponent, false,
	"",
    278,	"Recycle",	NormalType,	Status,	Smart,	10,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    279,	"Revenge",	FightingType,	Physical,	Tough,	10,	60,	100,	III,	MNoEffect,	Opponent, true,
	"",
    280,	"Brick Break",	FightingType,	Physical,	Cool,	15,	75,	100,	III,	MNoEffect,	Opponent, true,
	"",
    281,	"Yawn",	NormalType,	Status,	Cute,	10,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    282,	"Knock Off",	DarkType,	Physical,	Smart,	20,	65,	100,	III,	MNoEffect,	Opponent, true,
	"",
    283,	"Endeavor",	NormalType,	Physical,	Tough,	5,	-1,	100,	III,	MNoEffect,	Opponent, true,
	"",
    284,	"Eruption",	FireType,	Special,	Beauty,	5,	150,	100,	III,	MNoEffect,	Opponent, false,
	"",
    285,	"Skill Swap",	PsychicType,	Status,	Smart,	10,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    286,	"Imprison",	PsychicType,	Status,	Smart,	10,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    287,	"Refresh",	NormalType,	Status,	Cute,	20,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    288,	"Grudge",	GhostType,	Status,	Tough,	5,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    289,	"Snatch",	DarkType,	Status,	Smart,	10,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    290,	"Secret Power",	NormalType,	Physical,	Smart,	20,	70,	100,	III,	MNoEffect,	Opponent, false,
	"",
    291,	"Dive",	WaterType,	Physical,	Beauty,	10,	80,	100,	III,	MNoEffect,	Opponent, true,
	"",
    292,	"Arm Thrust",	FightingType,	Physical,	Tough,	20,	15,	100,	III,	MNoEffect,	Opponent, true,
	"",
    293,	"Camouflage",	NormalType,	Status,	Smart,	20,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    294,	"Tail Glow",	BugType,	Status,	Beauty,	20,	-1,	100,	III,	MUpSpA3,	Self, false,
	"",
    295,	"Luster Purge",	PsychicType,	Special,	Smart,	5,	70,	100,	III,	MNoEffect,	Opponent, false,
	"",
    296,	"Mist Ball",	PsychicType,	Special,	Smart,	5,	70,	100,	III,	MNoEffect,	Opponent, false,
	"",
    297,	"Feather Dance",	FlyingType,	Status,	Beauty,	15,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    298,	"Teeter Dance",	NormalType,	Status,	Cute,	20,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    299,	"Blaze Kick",	FireType,	Physical,	Beauty,	10,	85,	90,	III,	MNoEffect,	Opponent, true,
	"",
    300,	"Mud Sport",	GroundType,	Status,	Cute,	15,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    301,	"Ice Ball",	IceType,	Physical,	Beauty,	20,	30,	90,	III,	MNoEffect,	Opponent, true,
	"",
    302,	"Needle Arm",	GrassType,	Physical,	Smart,	15,	60,	100,	III,	MNoEffect,	Opponent, true,
	"",
    303,	"Slack Off",	NormalType,	Status,	Cute,	10,	-1,	100,	III,	MHeal50,	Self, false,
	"",
    304,	"Hyper Voice",	NormalType,	Special,	Cool,	10,	90,	100,	III,	MNoEffect,	Opponent, false,
	"",
    305,	"Poison Fang",	PoisonType,	Physical,	Smart,	15,	50,	100,	III,	MNoEffect,	Opponent, true,
	"",
    306,	"Crush Claw",	NormalType,	Physical,	Cool,	10,	75,	95,	III,	MNoEffect,	Opponent, true,
	"",
    307,	"Blast Burn",	FireType,	Special,	Beauty,	5,	150,	90,	III,	MRecharge,	Opponent, false,
	"",
    308,	"Hydro Cannon",	WaterType,	Special,	Beauty,	5,	150,	90,	III,	MRecharge,	Opponent, false,
	"",
    309,	"Meteor Mash",	SteelType,	Physical,	Cool,	10,	90,	90,	III,	MNoEffect,	Opponent, true,
	"",
    310,	"Astonish",	GhostType,	Physical,	Smart,	15,	30,	100,	III,	MNoEffect,	Opponent, true,
	"",
    311,	"Weather Ball",	NormalType,	Special,	Smart,	10,	50,	100,	III,	MNoEffect,	Opponent, false,
	"",
    312,	"Aromatherapy",	GrassType,	Status,	Smart,	5,	-1,	-1,	III,	MNoEffect,	Opponent, false,
	"",
    313,	"Fake Tears",	DarkType,	Status,	Smart,	20,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    314,	"Air Cutter",	FlyingType,	Special,	Cool,	25,	60,	95,	III,	MHighCrit,	Opponent, false,
	"",
    315,	"Overheat",	FireType,	Special,	Beauty,	5,	130,	90,	III,	MOverheat,	Opponent, false,
	"",
    316,	"Odor Sleuth",	NormalType,	Status,	Smart,	40,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    317,	"Rock Tomb",	RockType,	Physical,	Smart,	15,	60,	95,	III,	MNoEffect,	Opponent, false,
	"",
    318,	"Silver Wind",	BugType,	Special,	Beauty,	5,	60,	100,	III,	MUpAll10,	Opponent, false,
	"",
    319,	"Metal Sound",	SteelType,	Status,	Smart,	40,	-1,	85,	III,	MNoEffect,	Opponent, false,
	"",
    320,	"Grass Whistle",	GrassType,	Status,	Smart,	15,	-1,	55,	III,	MNoEffect,	Opponent, false,
	"",
    321,	"Tickle",	NormalType,	Status,	Cute,	20,	-1,	100,	III,	MLowerAttDef,	Opponent, false,
	"",
    322,	"Cosmic Power",	PsychicType,	Status,	Cool,	20,	-1,	-1,	III,	MUpDefSpD,	Self, false,
	"",
    323,	"Water Spout",	WaterType,	Special,	Beauty,	5,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    324,	"Signal Beam",	BugType,	Special,	Beauty,	15,	75,	100,	III,	MConfuse10,	Opponent, false,
	"",
    325,	"Shadow Punch",	GhostType,	Physical,	Smart,	20,	60,	-1,	III,	MNeverMiss,	Opponent, true,
	"",
    326,	"Extrasensory",	PsychicType,	Special,	Cool,	20,	80,	100,	III,	MNoEffect,	Opponent, false,
	"",
    327,	"Sky Uppercut",	FightingType,	Physical,	Cool,	15,	85,	90,	III,	MNoEffect,	Opponent, true,
	"",
    328,	"Sand Tomb",	GroundType,	Physical,	Smart,	15,	35,	85,	III,	MSandTomb,	Opponent, false,
	"",
    329,	"Sheer Cold",	IceType,	Special,	Beauty,	5,	-1,	30,	III,	MOHKO,	Opponent, false,
	"",
    330,	"Muddy Water",	WaterType,	Special,	Tough,	10,	90,	85,	III,	MNoEffect,	Opponent, false,
	"",
    331,	"Bullet Seed",	GrassType,	Physical,	Cool,	30,	25,	100,	III,	MNoEffect,	Opponent, false,
	"",
    332,	"Aerial Ace",	FlyingType,	Physical,	Cool,	20,	60,	-1,	III,	MNeverMiss,	Opponent, true,
	"",
    333,	"Icicle Spear",	IceType,	Physical,	Beauty,	30,	25,	100,	III,	MNoEffect,	Opponent, false,
	"",
    334,	"Iron Defense",	SteelType,	Status,	Tough,	15,	-1,	-1,	III,	MUpDef2,	Self, false,
	"",
    335,	"Block",	NormalType,	Status,	Cute,	5,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    336,	"Howl",	NormalType,	Status,	Cool,	40,	-1,	-1,	III,	MNoEffect,	Opponent, false,
	"",
    337,	"Dragon Claw",	DragonType,	Physical,	Cool,	15,	80,	100,	III,	MNoEffect,	Opponent, true,
	"",
    338,	"Frenzy Plant",	GrassType,	Special,	Cool,	5,	150,	90,	III,	MRecharge,	Opponent, false,
	"",
    339,	"Bulk Up",	FightingType,	Status,	Beauty,	20,	-1,	-1,	III,	MUpAttDef,	Self, false,
	"",
    340,	"Bounce",	FlyingType,	Physical,	Cute,	5,	85,	85,	III,	MNoEffect,	Opponent, true,
	"",
    341,	"Mud Shot",	GroundType,	Special,	Tough,	15,	55,	95,	III,	MNoEffect,	Opponent, false,
	"",
    342,	"Poison Tail",	PoisonType,	Physical,	Smart,	25,	50,	100,	III,	MNoEffect,	Opponent, true,
	"",
    343,	"Covet",	NormalType,	Physical,	Cute,	25,	60,	100,	III,	MNoEffect,	Opponent, true,
	"",
    344,	"Volt Tackle",	ElectricType,	Physical,	Cool,	15,	120,	100,	III,	MRecoil33,	Opponent, true,
	"",
    345,	"Magical Leaf",	GrassType,	Special,	Beauty,	20,	60,	-1,	III,	MNoEffect,	Opponent, false,
	"",
    346,	"Water Sport",	WaterType,	Status,	Cute,	15,	-1,	100,	III,	MNoEffect,	Opponent, false,
	"",
    347,	"Calm Mind",	PsychicType,	Status,	Smart,	20,	-1,	-1,	III,	MUpSpASpD,	Self, false,
	"",
    348,	"Leaf Blade",	GrassType,	Physical,	Cool,	15,	90,	100,	III,	MNoEffect,	Opponent, true,
	"",
    349,	"Dragon Dance",	DragonType,	Status,	Cool,	20,	-1,	-1,	III,	MUpAttSpe,	Self, false,
	"",
    350,	"Rock Blast",	RockType,	Physical,	Tough,	10,	25,	90,	III,	MNoEffect,	Opponent, false,
	"",
    351,	"Shock Wave",	ElectricType,	Special,	Cool,	20,	60,	-1,	III,	MNeverMiss,	Opponent, false,
	"",
    352,	"Water Pulse",	WaterType,	Special,	Beauty,	20,	60,	100,	III,	MConfuse20,	Opponent, false,
	"",
    353,	"Doom Desire",	SteelType,	Special,	Cool,	5,	140,	100,	III,	MNoEffect,	Opponent, false,
	"",
    354,	"Psycho Boost",	PsychicType,	Special,	Smart,	5,	140,	90,	III,	MOverheat,	Opponent, false,
	"",
    355,	"Roost",	FlyingType,	Status,	Cool,	10,	-1,	-1,	IV,	MHeal50,	Self, false,
	"",
    356,	"Gravity",	PsychicType,	Status,	Beauty,	5,	-1,	-1,	IV,	MGravity,	None, false,
	"",
    357,	"Miracle Eye",	PsychicType,	Status,	Cute,	40,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    358,	"Wake-Up Slap",	FightingType,	Physical,	Smart,	10,	70,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    359,	"Hammer Arm",	FightingType,	Physical,	Cool,	10,	100,	90,	IV,	MNoEffect,	Opponent, true,
	"",
    360,	"Gyro Ball",	SteelType,	Physical,	Beauty,	5,	-1,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    361,	"Healing Wish",	PsychicType,	Status,	Cute,	10,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    362,	"Brine",	WaterType,	Special,	Smart,	10,	65,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    363,	"Natural Gift",	NormalType,	Physical,	Cool,	15,	-1,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    364,	"Feint",	NormalType,	Physical,	Beauty,	10,	30,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    365,	"Pluck",	FlyingType,	Physical,	Cute,	20,	60,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    366,	"Tailwind",	FlyingType,	Status,	Smart,	15,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    367,	"Acupressure",	NormalType,	Status,	Cool,	30,	-1,	-1,	IV,	MUpRnd,	Opponent, false,
	"",
    368,	"Metal Burst",	SteelType,	Physical,	Beauty,	10,	-1,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    369,	"U-turn",	BugType,	Physical,	Cute,	20,	70,	100,	IV,	MBatonPass,	Opponent, true,
	"",
    370,	"Close Combat",	FightingType,	Physical,	Smart,	5,	120,	100,	IV,	MCloseCombat,	Opponent, true,
	"",
    371,	"Payback",	DarkType,	Physical,	Cool,	10,	50,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    372,	"Assurance",	DarkType,	Physical,	Beauty,	10,	60,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    373,	"Embargo",	DarkType,	Status,	Cute,	15,	-1,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    374,	"Fling",	DarkType,	Physical,	Tough,	10,	-1,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    375,	"Psycho Shift",	PsychicType,	Status,	Cool,	10,	-1,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    376,	"Trump Card",	NormalType,	Special,	Cool,	5,	-1,	-1,	IV,	MNoEffect,	Opponent, true,
	"",
    377,	"Heal Block",	PsychicType,	Status,	Cute,	15,	-1,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    378,	"Wring Out",	NormalType,	Special,	Smart,	5,	-1,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    379,	"Power Trick",	PsychicType,	Status,	Cool,	10,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    380,	"Gastro Acid",	PoisonType,	Status,	Beauty,	10,	-1,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    381,	"Lucky Chant",	NormalType,	Status,	Cute,	30,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    382,	"Me First",	NormalType,	Status,	Cute,	20,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    383,	"Copycat",	NormalType,	Status,	Cool,	20,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    384,	"Power Swap",	PsychicType,	Status,	Beauty,	10,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    385,	"Guard Swap",	PsychicType,	Status,	Cute,	10,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    386,	"Punishment",	DarkType,	Physical,	Smart,	5,	-1,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    387,	"Last Resort",	NormalType,	Physical,	Cute,	5,	140,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    388,	"Worry Seed",	GrassType,	Status,	Beauty,	10,	-1,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    389,	"Sucker Punch",	DarkType,	Physical,	Smart,	5,	80,	100,	IV,	MSuckerPunch,	Opponent, true,
	"",
    390,	"Toxic Spikes",	PoisonType,	Status,	Smart,	20,	-1,	-1,	IV,	MHazard,	Opponent, false,
	"",
    391,	"Heart Swap",	PsychicType,	Status,	Cool,	10,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    392,	"Aqua Ring",	WaterType,	Status,	Beauty,	20,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    393,	"Magnet Rise",	ElectricType,	Status,	Cute,	10,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    394,	"Flare Blitz",	FireType,	Physical,	Smart,	15,	120,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    395,	"Force Palm",	FightingType,	Physical,	Cool,	10,	60,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    396,	"Aura Sphere",	FightingType,	Special,	Beauty,	20,	80,	-1,	IV,	MNeverMiss,	Opponent, false,
	"",
    397,	"Rock Polish",	RockType,	Status,	Tough,	20,	-1,	-1,	IV,	MUpSpe2,	Self, false,
	"",
    398,	"Poison Jab",	PoisonType,	Physical,	Smart,	20,	80,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    399,	"Dark Pulse",	DarkType,	Special,	Cool,	15,	80,	100,	IV,	MFlinch20,	Opponent, false,
	"",
    400,	"Night Slash",	DarkType,	Physical,	Beauty,	15,	70,	100,	IV,	MHighCrit,	Opponent, true,
	"",
    401,	"Aqua Tail",	WaterType,	Physical,	Cute,	10,	90,	90,	IV,	MNoEffect,	Opponent, true,
	"",
    402,	"Seed Bomb",	GrassType,	Physical,	Smart,	15,	80,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    403,	"Air Slash",	FlyingType,	Special,	Cool,	15,	75,	95,	IV,	MFlinch30,	Opponent, false,
	"",
    404,	"X-Scissor",	BugType,	Physical,	Beauty,	15,	80,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    405,	"Bug Buzz",	BugType,	Special,	Cute,	10,	90,	100,	IV,	MLowerSpD10,	Opponent, false,
	"",
    406,	"Dragon Pulse",	DragonType,	Special,	Smart,	10,	85,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    407,	"Dragon Rush",	DragonType,	Physical,	Cool,	10,	100,	75,	IV,	MNoEffect,	Opponent, true,
	"",
    408,	"Power Gem",	RockType,	Special,	Beauty,	20,	80,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    409,	"Drain Punch",	FightingType,	Physical,	Beauty,	10,	75,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    410,	"Vacuum Wave",	FightingType,	Special,	Smart,	30,	40,	100,	IV,	MMoveFirst,	Opponent, false,
	"",
    411,	"Focus Blast",	FightingType,	Special,	Cool,	5,	120,	70,	IV,	MNoEffect,	Opponent, false,
	"",
    412,	"Energy Ball",	GrassType,	Special,	Beauty,	10,	90,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    413,	"Brave Bird",	FlyingType,	Physical,	Cute,	15,	120,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    414,	"Earth Power",	GroundType,	Special,	Smart,	10,	90,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    415,	"Switcheroo",	DarkType,	Status,	Cool,	10,	-1,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    416,	"Giga Impact",	NormalType,	Physical,	Beauty,	5,	150,	90,	IV,	MRecharge,	Opponent, true,
	"",
    417,	"Nasty Plot",	DarkType,	Status,	Cute,	20,	-1,	-1,	IV,	MUpSpA2,	Self, false,
	"",
    418,	"Bullet Punch",	SteelType,	Physical,	Smart,	30,	40,	100,	IV,	MMoveFirst,	Opponent, true,
	"",
    419,	"Avalanche",	IceType,	Physical,	Cool,	10,	60,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    420,	"Ice Shard",	IceType,	Physical,	Beauty,	30,	40,	100,	IV,	MMoveFirst,	Opponent, false,
	"",
    421,	"Shadow Claw",	GhostType,	Physical,	Cute,	15,	70,	100,	IV,	MHighCrit,	Opponent, true,
	"",
    422,	"Thunder Fang",	ElectricType,	Physical,	Smart,	15,	65,	95,	IV,	MParalyze10,	Opponent, true,
	"",
    423,	"Ice Fang",	IceType,	Physical,	Cool,	15,	65,	95,	IV,	MNoEffect,	Opponent, true,
	"",
    424,	"Fire Fang",	FireType,	Physical,	Beauty,	15,	65,	95,	IV,	MNoEffect,	Opponent, true,
	"",
    425,	"Shadow Sneak",	GhostType,	Physical,	Smart,	30,	40,	100,	IV,	MMoveFirst,	Opponent, true,
	"",
    426,	"Mud Bomb",	GroundType,	Special,	Smart,	10,	65,	85,	IV,	MNoEffect,	Opponent, false,
	"",
    427,	"Psycho Cut",	PsychicType,	Physical,	Cool,	20,	70,	100,	IV,	MHighCrit,	Opponent, false,
	"",
    428,	"Zen Headbutt",	PsychicType,	Physical,	Beauty,	15,	80,	90,	IV,	MFlinch20,	Opponent, true,
	"",
    429,	"Mirror Shot",	SteelType,	Special,	Cute,	10,	65,	85,	IV,	MNoEffect,	Opponent, false,
	"",
    430,	"Flash Cannon",	SteelType,	Special,	Smart,	10,	80,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    431,	"Rock Climb",	NormalType,	Physical,	Cool,	20,	90,	85,	IV,	MNoEffect,	Opponent, true,
	"",
    432,	"Defog",	FlyingType,	Status,	Beauty,	15,	-1,	-1,	IV,	MDehazard,	All, false,
	"",
    433,	"Trick Room",	PsychicType,	Status,	Cute,	5,	-1,	-1,	IV,	MTrickRoom,	None, false,
	"",
    434,	"Draco Meteor",	DragonType,	Special,	Smart,	5,	130,	90,	IV,	MOverheat,	Opponent, false,
	"",
    435,	"Discharge",	ElectricType,	Special,	Cool,	15,	80,	100,	IV,	MParalyze30,	Opponent, false,
	"",
    436,	"Lava Plume",	FireType,	Special,	Tough,	15,	80,	100,	IV,	MBurn30,	Opponent, false,
	"",
    437,	"Leaf Storm",	GrassType,	Special,	Cute,	5,	130,	90,	IV,	MOverheat,	Opponent, false,
	"",
    438,	"Power Whip",	GrassType,	Physical,	Beauty,	10,	120,	85,	IV,	MNoEffect,	Opponent, true,
	"",
    439,	"Rock Wrecker",	RockType,	Physical,	Tough,	5,	150,	90,	IV,	MRecharge,	Opponent, false,
	"",
    440,	"Cross Poison",	PoisonType,	Physical,	Cool,	20,	70,	100,	IV,	MHighCrit,	Opponent, true,
	"",
    441,	"Gunk Shot",	PoisonType,	Physical,	Cool,	5,	120,	80,	IV,	MNoEffect,	Opponent, false,
	"",
    442,	"Iron Head",	SteelType,	Physical,	Tough,	15,	80,	100,	IV,	MFlinch30,	Opponent, true,
	"",
    443,	"Magnet Bomb",	SteelType,	Physical,	Cool,	20,	60,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    444,	"Stone Edge",	RockType,	Physical,	Tough,	5,	100,	80,	IV,	MHighCrit,	Opponent, false,
	"",
    445,	"Captivate",	NormalType,	Status,	Beauty,	20,	-1,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    446,	"Stealth Rock",	RockType,	Status,	Cool,	20,	-1,	-1,	IV,	MHazard,	None, false,
	"",
    447,	"Grass Knot",	GrassType,	Special,	Smart,	20,	-1,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    448,	"Chatter",	FlyingType,	Special,	Smart,	20,	65,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    449,	"Judgment",	NormalType,	Special,	Smart,	10,	100,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    450,	"Bug Bite",	BugType,	Physical,	Tough,	20,	60,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    451,	"Charge Beam",	ElectricType,	Special,	Beauty,	10,	50,	90,	IV,	MNoEffect,	Opponent, false,
	"",
    452,	"Wood Hammer",	GrassType,	Physical,	Tough,	15,	120,	100,	IV,	MRecoil33,	Opponent, true,
	"",
    453,	"Aqua Jet",	WaterType,	Physical,	Beauty,	20,	40,	100,	IV,	MMoveFirst,	Opponent, true,
	"",
    454,	"Attack Order",	BugType,	Physical,	Smart,	15,	90,	100,	IV,	MNoEffect,	Opponent, false,
	"",
    455,	"Defend Order",	BugType,	Status,	Smart,	10,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    456,	"Heal Order",	BugType,	Status,	Smart,	10,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    457,	"Head Smash",	RockType,	Physical,	Tough,	5,	150,	80,	IV,	MNoEffect,	Opponent, true,
	"",
    458,	"Double Hit",	NormalType,	Physical,	Smart,	10,	35,	90,	IV,	MNoEffect,	Opponent, true,
	"",
    459,	"Roar of Time",	DragonType,	Special,	Cool,	5,	150,	90,	IV,	MNoEffect,	Opponent, false,
	"",
    460,	"Spacial Rend",	DragonType,	Special,	Tough,	5,	100,	95,	IV,	MHighCrit,	Opponent, false,
	"",
    461,	"Lunar Dance",	PsychicType,	Status,	Beauty,	10,	-1,	-1,	IV,	MNoEffect,	Opponent, false,
	"",
    462,	"Crush Grip",	NormalType,	Physical,	Tough,	5,	-1,	100,	IV,	MNoEffect,	Opponent, true,
	"",
    463,	"Magma Storm",	FireType,	Special,	Tough,	5,	100,	75,	IV,	MNoEffect,	Opponent, false,
	"",
    464,	"Dark Void",	DarkType,	Status,	Smart,	10,	-1,	80,	IV,	MNoEffect,	Opponent, false,
	"",
    465,	"Seed Flare",	GrassType,	Special,	Cool,	5,	120,	85,	IV,	MLowerSpD40,	Opponent, false,
	"",
    466,	"Ominous Wind",	GhostType,	Special,	Smart,	5,	60,	100,	IV,	MUpAll10,	Opponent, false,
	"",
    467,	"Shadow Force",	GhostType,	Physical,	Smart,	5,	120,	100,	IV,	MShadowForce,	Opponent, true,
	"",
    468,	"Hone Claws",	DarkType,	Status,	UnknownStat,	15,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    469,	"Wide Guard",	RockType,	Status,	UnknownStat,	10,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    470,	"Guard Split",	PsychicType,	Status,	UnknownStat,	10,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    471,	"Power Split",	PsychicType,	Status,	UnknownStat,	10,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    472,	"Wonder Room",	PsychicType,	Status,	UnknownStat,	10,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    473,	"Psyshock",	PsychicType,	Special,	UnknownStat,	10,	80,	100,	V,	MShockDef,	Opponent, false,
	"",
    474,	"Venoshock",	PoisonType,	Special,	UnknownStat,	10,	65,	100,	V,	MNoEffect,	Opponent, false,
	"",
    475,	"Autotomize",	SteelType,	Status,	UnknownStat,	15,	-1,	-1,	V,	MUpSpe2,	Self, false,
	"",
    476,	"Rage Powder",	BugType,	Status,	UnknownStat,	20,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    477,	"Telekinesis",	PsychicType,	Status,	UnknownStat,	15,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    478,	"Magic Room",	PsychicType,	Status,	UnknownStat,	10,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    479,	"Smack Down",	RockType,	Physical,	UnknownStat,	15,	50,	100,	V,	MNoEffect,	Opponent, false,
	"",
    480,	"Storm Throw",	FightingType,	Physical,	UnknownStat,	10,	60,	100,	V,	MCrit100,	Opponent, true,
	"",
    481,	"Flame Burst",	FireType,	Special,	UnknownStat,	15,	70,	100,	V,	MNoEffect,	Opponent, false,
	"",
    482,	"Sludge Wave",	PoisonType,	Special,	UnknownStat,	10,	95,	100,	V,	MPoison10,	Opponent, false,
	"",
    483,	"Quiver Dance",	BugType,	Status,	UnknownStat,	20,	-1,	-1,	V,	MUpSpASpD,	Self, false,
	"",
    484,	"Heavy Slam",	SteelType,	Physical,	UnknownStat,	10,	-1,	100,	V,	MNoEffect,	Opponent, true,
	"",
    485,	"Synchronoise",	PsychicType,	Special,	UnknownStat,	15,	120,	100,	V,	MNoEffect,	Opponent, false,
	"",
    486,	"Electro Ball",	ElectricType,	Special,	UnknownStat,	10,	-1,	100,	V,	MNoEffect,	Opponent, false,
	"",
    487,	"Soak",	WaterType,	Status,	UnknownStat,	20,	-1,	100,	V,	MNoEffect,	Opponent, false,
	"",
    488,	"Flame Charge",	FireType,	Physical,	UnknownStat,	20,	50,	100,	V,	MNoEffect,	Opponent, true,
	"",
    489,	"Coil",	PoisonType,	Status,	UnknownStat,	20,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    490,	"Low Sweep",	FightingType,	Physical,	UnknownStat,	20,	65,	100,	V,	MNoEffect,	Opponent, true,
	"",
    491,	"Acid Spray",	PoisonType,	Special,	UnknownStat,	20,	40,	100,	V,	MLowerSpD2,	Opponent, false,
	"",
    492,	"Foul Play",	DarkType,	Physical,	UnknownStat,	15,	95,	100,	V,	MNoEffect,	Opponent, true,
	"",
    493,	"Simple Beam",	NormalType,	Status,	UnknownStat,	15,	-1,	100,	V,	MNoEffect,	Opponent, false,
	"",
    494,	"Entrainment",	NormalType,	Status,	UnknownStat,	15,	-1,	100,	V,	MNoEffect,	Opponent, false,
	"",
    495,	"After You",	NormalType,	Status,	UnknownStat,	15,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    496,	"Round",	NormalType,	Special,	UnknownStat,	15,	60,	100,	V,	MNoEffect,	Opponent, false,
	"",
    497,	"Echoed Voice",	NormalType,	Special,	UnknownStat,	15,	40,	100,	V,	MNoEffect,	Opponent, false,
	"",
    498,	"Chip Away",	NormalType,	Physical,	UnknownStat,	20,	70,	100,	V,	MNoEffect,	Opponent, true,
	"",
    499,	"Clear Smog",	PoisonType,	Special,	UnknownStat,	15,	50,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    500,	"Stored Power",	PsychicType,	Special,	UnknownStat,	10,	20,	100,	V,	MNoEffect,	Opponent, false,
	"",
    501,	"Quick Guard",	FightingType,	Status,	UnknownStat,	15,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    502,	"Ally Switch",	PsychicType,	Status,	UnknownStat,	15,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    503,	"Scald",	WaterType,	Special,	UnknownStat,	15,	80,	100,	V,	MBurn30,	Opponent, false,
	"",
    504,	"Shell Smash",	NormalType,	Status,	UnknownStat,	15,	-1,	-1,	V,	MLowerDefSpDUpAtt2SpA2Spe2,	Self, false,
	"",
    505,	"Heal Pulse",	PsychicType,	Status,	UnknownStat,	10,	-1,	-1,	V,	MHeal50,	Opponent, false,
	"",
    506,	"Hex",	GhostType,	Special,	UnknownStat,	10,	65,	100,	V,	MNoEffect,	Opponent, false,
	"",
    507,	"Sky Drop",	FlyingType,	Physical,	UnknownStat,	10,	60,	100,	V,	MSkyDrop,	Opponent, true,
	"",
    508,	"Shift Gear",	SteelType,	Status,	UnknownStat,	10,	-1,	-1,	V,	MUpAttSpe2,	Self, false,
	"",
    509,	"Circle Throw",	FightingType,	Physical,	UnknownStat,	10,	60,	90,	V,	MNoEffect,	Opponent, true,
	"",
    510,	"Incinerate",	FireType,	Special,	UnknownStat,	15,	60,	100,	V,	MNoEffect,	Opponent, false,
	"",
    511,	"Quash",	DarkType,	Status,	UnknownStat,	15,	-1,	100,	V,	MNoEffect,	Opponent, false,
	"",
    512,	"Acrobatics",	FlyingType,	Physical,	UnknownStat,	15,	55,	100,	V,	MNoEffect,	Opponent, true,
	"",
    513,	"Reflect Type",	NormalType,	Status,	UnknownStat,	15,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    514,	"Retaliate",	NormalType,	Physical,	UnknownStat,	5,	70,	100,	V,	MNoEffect,	Opponent, true,
	"",
    515,	"Final Gambit",	FightingType,	Special,	UnknownStat,	5,	-1,	100,	V,	MNoEffect,	Opponent, true,
	"",
    516,	"Bestow",	NormalType,	Status,	UnknownStat,	15,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    517,	"Inferno",	FireType,	Special,	UnknownStat,	5,	100,	50,	V,	MNoEffect,	Opponent, false,
	"",
    518,	"Water Pledge",	WaterType,	Special,	UnknownStat,	10,	80,	100,	V,	MNoEffect,	Opponent, false,
	"",
    519,	"Fire Pledge",	FireType,	Special,	UnknownStat,	10,	80,	100,	V,	MNoEffect,	Opponent, false,
	"",
    520,	"Grass Pledge",	GrassType,	Special,	UnknownStat,	10,	80,	100,	V,	MNoEffect,	Opponent, false,
	"",
    521,	"Volt Switch",	ElectricType,	Special,	UnknownStat,	20,	70,	100,	V,	MBatonPass,	Opponent, false,
	"",
    522,	"Struggle Bug",	BugType,	Special,	UnknownStat,	20,	50,	100,	V,	MLowerSpA100,	Opponent, false,
	"",
    523,	"Bulldoze",	GroundType,	Physical,	UnknownStat,	20,	60,	100,	V,	MNoEffect,	Opponent, false,
	"",
    524,	"Frost Breath",	IceType,	Special,	UnknownStat,	10,	60,	90,	V,	MCrit100,	Opponent, false,
	"",
    525,	"Dragon Tail",	DragonType,	Physical,	UnknownStat,	10,	60,	90,	V,	MNoEffect,	Opponent, true,
	"",
    526,	"Work Up",	NormalType,	Status,	UnknownStat,	30,	-1,	-1,	V,	MUpAttSpA,	Self, false,
	"",
    527,	"Electroweb",	ElectricType,	Special,	UnknownStat,	15,	55,	95,	V,	MNoEffect,	Opponent, false,
	"",
    528,	"Wild Charge",	ElectricType,	Physical,	UnknownStat,	15,	90,	100,	V,	MRecoil25,	Opponent, true,
	"",
    529,	"Drill Run",	GroundType,	Physical,	UnknownStat,	10,	80,	95,	V,	MNoEffect,	Opponent, true,
	"",
    530,	"Dual Chop",	DragonType,	Physical,	UnknownStat,	15,	40,	90,	V,	MNoEffect,	Opponent, true,
	"",
    531,	"Heart Stamp",	PsychicType,	Physical,	UnknownStat,	25,	60,	100,	V,	MNoEffect,	Opponent, true,
	"",
    532,	"Horn Leech",	GrassType,	Physical,	UnknownStat,	10,	75,	100,	V,	MNoEffect,	Opponent, true,
	"",
    533,	"Sacred Sword",	FightingType,	Physical,	UnknownStat,	15,	90,	100,	V,	MNoEffect,	Opponent, true,
	"",
    534,	"Razor Shell",	WaterType,	Physical,	UnknownStat,	10,	75,	95,	V,	MNoEffect,	Opponent, true,
	"",
    535,	"Heat Crash",	FireType,	Physical,	UnknownStat,	10,	-1,	100,	V,	MNoEffect,	Opponent, true,
	"",
    536,	"Leaf Tornado",	GrassType,	Special,	UnknownStat,	10,	65,	90,	V,	MNoEffect,	Opponent, false,
	"",
    537,	"Steamroller",	BugType,	Physical,	UnknownStat,	20,	65,	100,	V,	MFlinch30,	Opponent, true,
	"",
    538,	"Cotton Guard",	GrassType,	Status,	UnknownStat,	10,	-1,	-1,	V,	MNoEffect,	Opponent, false,
	"",
    539,	"Night Daze",	DarkType,	Special,	UnknownStat,	10,	85,	95,	V,	MNoEffect,	Opponent, false,
	"",
    540,	"Psystrike",	PsychicType,	Special,	UnknownStat,	10,	100,	100,	V,	MShockDef,	Opponent, false,
	"",
    541,	"Tail Slap",	NormalType,	Physical,	UnknownStat,	10,	25,	85,	V,	MMultiHit,	Opponent, true,
	"",
    542,	"Hurricane",	FlyingType,	Special,	UnknownStat,	10,	110,	70,	V,	MNoEffect,	Opponent, false,
	"",
    543,	"Head Charge",	NormalType,	Physical,	UnknownStat,	15,	120,	100,	V,	MNoEffect,	Opponent, true,
	"",
    544,	"Gear Grind",	SteelType,	Physical,	UnknownStat,	15,	50,	85,	V,	MNoEffect,	Opponent, false,
	"",
    545,	"Searing Shot",	FireType,	Special,	UnknownStat,	5,	100,	100,	V,	MBurn30,	Opponent, false,
	"",
    546,	"Techno Blast",	NormalType,	Special,	UnknownStat,	5,	120,	100,	V,	MNoEffect,	Opponent, false,
	"",
    547,	"Relic Song",	NormalType,	Special,	UnknownStat,	10,	75,	100,	V,	MNoEffect,	Opponent, false,
	"",
    548,	"Secret Sword",	FightingType,	Special,	UnknownStat,	10,	85,	100,	V,	MShockDef,	Opponent, false,
	"",
    549,	"Glaciate",	IceType,	Special,	UnknownStat,	10,	65,	95,	V,	MNoEffect,	Opponent, false,
	"",
    550,	"Bolt Strike",	ElectricType,	Physical,	UnknownStat,	5,	130,	85,	V,	MNoEffect,	Opponent, true,
	"",
    551,	"Blue Flare",	FireType,	Special,	UnknownStat,	5,	130,	85,	V,	MNoEffect,	Opponent, false,
	"",
    552,	"Fiery Dance",	FireType,	Special,	UnknownStat,	10,	80,	100,	V,	MNoEffect,	Opponent, false,
	"",
    553,	"Freeze Shock",	IceType,	Physical,	UnknownStat,	5,	140,	90,	V,	MNoEffect,	Opponent, false,
	"",
    554,	"Ice Burn",	IceType,	Special,	UnknownStat,	5,	140,	90,	V,	MNoEffect,	Opponent, false,
	"",
    555,	"Snarl",	DarkType,	Special,	UnknownStat,	15,	55,	95,	V,	MLowerSpA100,	Opponent, false,
	"",
    556,	"Icicle Crash",	IceType,	Physical,	UnknownStat,	10,	85,	90,	V,	MNoEffect,	Opponent, false,
	"",
    557,	"V-create",	FireType,	Physical,	UnknownStat,	5,	180,	95,	V,	MLowerDefSpDSpe,	Opponent, true,
	"",
    558,	"Fusion Flare",	FireType,	Special,	UnknownStat,	5,	100,	100,	V,	MNoEffect,	Opponent, false,
	"",
    559,	"Fusion Bolt",	ElectricType,	Physical,	UnknownStat,	5,	100,	100,	V,	MNoEffect,	Opponent, false,
	"",
    560,	"Flying Press",	FightingType,	Physical,	UnknownStat,	10,	80,	95,	VI,	MNoEffect,	Opponent, true,
	"",
    561,	"Mat Block",	FightingType,	Status,	UnknownStat,	10,	-1,	-1,	VI,	MShield,	None, false,
	"",
    562,	"Belch",	PoisonType,	Special,	UnknownStat,	10,	120,	90,	VI,	MNoEffect,	Opponent, false,
	"",
    563,	"Rototiller",	GroundType,	Status,	UnknownStat,	10,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    564,	"Sticky Web",	BugType,	Status,	UnknownStat,	20,	-1,	-1,	VI,	MHazard,	Opponent, false,
	"",
    565,	"Fell Stinger",	BugType,	Physical,	UnknownStat,	25,	30,	100,	VI,	MNoEffect,	Opponent, true,
	"",
    566,	"Phantom Force",	GhostType,	Physical,	UnknownStat,	10,	90,	100,	VI,	MNoEffect,	Opponent, true,
	"",
    567,	"Trick-or-Treat",	GhostType,	Status,	UnknownStat,	20,	-1,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    568,	"Noble Roar",	NormalType,	Status,	UnknownStat,	30,	-1,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    569,	"Ion Deluge",	ElectricType,	Status,	UnknownStat,	25,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    570,	"Parabolic Charge",	ElectricType,	Special,	UnknownStat,	20,	50,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    571,	"Forest's Curse",	GrassType,	Status,	UnknownStat,	20,	-1,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    572,	"Petal Blizzard",	GrassType,	Physical,	UnknownStat,	15,	90,	100,	VI,	MNoEffect,	Opponent, true,
	"",
    573,	"Freeze-Dry",	IceType,	Special,	UnknownStat,	20,	70,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    574,	"Disarming Voice",	FairyType,	Special,	UnknownStat,	15,	40,	-1,	VI,	MNeverMiss,	Opponent, false,
	"",
    575,	"Parting Shot",	DarkType,	Status,	UnknownStat,	20,	-1,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    576,	"Topsy-Turvy",	DarkType,	Status,	UnknownStat,	20,	-1,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    577,	"Draining Kiss",	FairyType,	Special,	UnknownStat,	10,	50,	100,	VI,	MDrain75,	Opponent, true,
	"",
    578,	"Crafty Shield",	FairyType,	Status,	UnknownStat,	10,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    579,	"Flower Shield",	FairyType,	Status,	UnknownStat,	10,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    580,	"Grassy Terrain",	GrassType,	Status,	UnknownStat,	10,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    581,	"Misty Terrain",	FairyType,	Status,	UnknownStat,	10,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    582,	"Electrify",	ElectricType,	Status,	UnknownStat,	20,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    583,	"Play Rough",	FairyType,	Physical,	UnknownStat,	10,	90,	90,	VI,	MNoEffect,	Opponent, true,
	"",
    584,	"Fairy Wind",	FairyType,	Special,	UnknownStat,	30,	40,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    585,	"Moonblast",	FairyType,	Special,	UnknownStat,	15,	95,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    586,	"Boomburst",	NormalType,	Special,	UnknownStat,	10,	140,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    587,	"Fairy Lock",	FairyType,	Status,	UnknownStat,	10,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    588,	"King's Shield",	SteelType,	Status,	UnknownStat,	10,	-1,	-1,	VI,	MShield,	Self, false,
	"",
    589,	"Play Nice",	NormalType,	Status,	UnknownStat,	20,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    590,	"Confide",	NormalType,	Status,	UnknownStat,	20,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    591,	"Diamond Storm",	RockType,	Physical,	UnknownStat,	5,	100,	95,	VI,	MNoEffect,	Opponent, true,
	"",
    592,	"???",	NoType,	Status,	UnknownStat,	-1,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    593,	"???",	NoType, Status,	UnknownStat,	-1,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    594,	"Water Shuriken",	WaterType,	Physical,	UnknownStat,	20,	15,	100,	VI,	MMultiHit,	Opponent, true,
	"",
    595,	"Mystical Fire",	FireType,	Special,	UnknownStat,	10,	65,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    596,	"Spiky Shield",	GrassType,	Status,	UnknownStat,	10,	-1,	-1,	VI,	MShield,	Opponent, false,
	"",
    597,	"Aromatic Mist",	FairyType,	Status,	UnknownStat,	20,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    598,	"Eerie Impulse",	ElectricType,	Status,	UnknownStat,	15,	-1,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    599,	"Venom Drench",	PoisonType,	Status,	UnknownStat,	20,	-1,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    600,	"Powder",	BugType,	Status,	UnknownStat,	20,	-1,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    601,	"Geomancy",	FairyType,	Status,	UnknownStat,	10,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    602,	"Magnetic Flux",	ElectricType,	Status,	UnknownStat,	20,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    603,	"Happy Hour",	NormalType,	Status,	UnknownStat,	30,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    604,	"Electric Terrain",	ElectricType,	Status,	UnknownStat,	10,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    605,	"Dazzling Gleam",	FairyType,	Special,	UnknownStat,	10,	80,	100,	VI,	MNoEffect,	Both, false,
	"",
    606,	"Celebrate",	NormalType,	Status,	UnknownStat,	40,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    607,	"???",	NoType,	Status,	UnknownStat,	-1,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    608,	"Baby-Doll Eyes",	FairyType,	Status,	UnknownStat,	30,	-1,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    609,	"Nuzzle",	ElectricType,	Physical,	UnknownStat,	20,	20,	100,	VI,	MNoEffect,	Opponent, true,
	"",
    610,	"Hold Back",	NormalType,	Physical,	UnknownStat,	40,	40,	100,	VI,	MNoEffect,	Opponent, true,
	"",
    611,	"Infestation",	BugType,	Special,	UnknownStat,	20,	20,	100,	VI,	MNoEffect,	Opponent, true,
	"",
    612,	"Power-Up Punch",	FightingType,	Physical,	UnknownStat,	20,	40,	100,	VI,	MNoEffect,	Opponent, true,
	"",
    613,	"Oblivion Wing",	FlyingType,	Special,	UnknownStat,	10,	80,	100,	VI,	MNoEffect,	Opponent, false,
	"",
    614,	"???",	NoType,	Status,	UnknownStat,	-1,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    615,	"???",	NoType,	Status,	UnknownStat,	-1,	-1,	-1,	VI,	MNoEffect,	Opponent, false,
	"",
    616,	"Land's Wrath", GroundType,	Physical,	UnknownStat,	10,	90,	100,	VI,	MNoEffect,	Opponent, true,
	"",
    617,    "Crimson Sunset",   NeutralType,    Special,    UnknownStat,    5,  -1, 100,    X,  MOHKO,  Opponent, false,
	"Sets off a nuclear blast that burns like the sun. The target will faint instantly if hit.",
    618,    "Dragonfire",   DragonType, Special,    UnknownStat,    10,  100,    100, X, MIgnoreDef100,   Opponent, false,
	"The user razes the target with mystical green flames that can burn through anything.",
    619,    "Radiant Blade",    LightType,  Physical,    UnknownStat,    5, 100,    100,        X,  MIgnoreDef100,  Opponent, false,
	"Generates a sword of light and attacks the foe. This move pierces through the target's defense.",
    620,    "Genesis",  LightType,  Special,    UnknownStat,    5,  180,    100,    X,  MRecharge,  Opponent, false,
	"The battlefield is covered with a blast of light that deals heavy damage to all Pokemon in range. The user must recharge for a turn.",
    621,    "Shining Strike",   LightType,  Physical,   UnknownStat,    5, 90, 100,    X,  MNoEffect,  Opponent, false,
	"The user strikes the target with dense light energy.",
    622,    "Angelfire",    LightType,  Special,   UnknownStat,    10, 80, 100,    X,  MIgnoreDef100,  Opponent, false,
	"The user razes the target with mystical golden flames that only burn the wicked. This move pierces through the target's defense.",
    623,    "Demonfire",    DarkType,   Special,   UnknownStat,    10, 80, 100,    X,  MIgnoreDef100,  Opponent, false,
	"The user razes the target with mystical violet flames that burn everything but the wicked. This move pierces through the target's defense.",
    624,    "Holy Sanction", LightType,  Status, UnknownStat,    5, -1, 100,    X,  MNoEffect,  Opponent, false,
	"Prevents all Pokemon from using attacking moves during the next turn.",
    625,    "Prohibition",  DarkType,   Status, UnknownStat,    5, -1, 100,    X,  MNoEffect,  Opponent, false,
	"Prevents all Pokemon from using non-attacking moves during the next turn.",
    626,    "Shining Ray",  LightType,  Special,    UnknownStat,    5, 95, 100,    X,  MIgnoreDef100,  Opponent, false,
	"The user fires a concentrated blast of light at the target that pierces its defense.",
    627,    "Sunfire",  FireType,   Special,    UnknownStat,    10, 80, 100,    X,  MIgnoreDef100,  Opponent, false,
	"The user attacks with a fireball of sun-hot flames that will burn through anything. This move pierces through the target's defense.",
    628,    "Moonfire", FairyType,  Special,    UnknownStat,    10, 80, 100,    X,  MIgnoreDef100,  Opponent, false,
	"The user attacks with a fireball of silver flames that will burn through anything. This move pierces through the target's defense.",
    629,    "Astrostorm",    FireType,   Special,    UnknownStat,    5,  100,    95, X,  MNoEffect,  Opponent, false,
	"The user summons meteors from another dimension to attack the opponent.",
    630,    "Astrostorm",   ElectricType,   Special,    UnknownStat,    5,  100,    95, X,  MNoEffect,  Opponent, false,
	"The user summons a thunderstorm from another dimension to attack the opponent.",
    631,    "Astrostorm", PoisonType, Special,    UnknownStat,    5,  100,    95, X,  MNoEffect,  Opponent, false,
	"The user summons a cloud of highly poisonous gas from another dimension to attack the opponent.",
    632,    "Astrostorm",   IceType,    Special,    UnknownStat,    5,  100,    95, X,  MNoEffect,  Opponent, false,
	"The user summons a blizzard from another dimension to attack the opponent.",
    633,    "Blitz",    LightType,  Physical,    UnknownStat,    25, 40, 100,    X,  MMoveFirst,  Opponent, true,
	"The user glows brightly and attacks the foe at a high speed.",
    634,    "Queen's Shield",   LightType,  Status, UnknownStat,    10, -1, -1, X,  MProtect,  Self, false,
    "Protects the user from damage. If the foe uses a special attacking move, their special attack will be lowered.",
    635,    "Bleak Midwinter",  IceType,    Special,    UnknownStat,    10, 100,    95, X,  MFreeze50,  Opponent, false,
    "The target is attacked with a powerful blizzard that will sap the warmth from anything. Will freeze the target with high probability.",
    636,    "Demolition",   FightingType,   Physical,   UnknownStat,    5,  130,    90, X,  MNoEffect, Opponent, true,
    "Unleashes a barrage of punches at full power, devestating the opponent.",
    637,    "Heaven's Mirror",  LightType,  Status, UnknownStat,    5,  -1, -1, X,  MProtect,   Self,   false,
    "Protects the user and reflects damage twofold. If unsuccessful, it lowers the user's Attack and Sp. Attack by two stages.",
    
    638,    "",  NoType, Physical,   UnknownStat,    -1, 40, -1, I,  MNoEffect,  Self,   false,
    "",
    639,    "", NoType, Status, UnknownStat,    -1, -1, -1, I,  MNoEffect,  Self,   false,
    ""
};

#endif /* defined(__pokemongame__MoveData__) */













































